"""Add updated_at to boards

Revision ID: c5487b123a48
Revises: xxxx_init
Create Date: 2025-06-14 04:59:18.043887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5487b123a48'
down_revision: Union[str, None] = 'xxxx_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    op.add_column('problems', sa.Column('input_description', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('output_description', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('input_example', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('output_example', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('memory_limit', sa.Integer(), nullable=True))
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.add_column('submissions', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('submissions', sa.Column('result', sa.String(length=20), nullable=True))
    op.add_column('submissions', sa.Column('stdout', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('stderr', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('submissions', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.drop_constraint(op.f('submissions_problem_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_problem_id_fkey'), 'submissions', 'problems', ['problem_id'], ['id'])
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.alter_column('submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'stderr')
    op.drop_column('submissions', 'stdout')
    op.drop_column('submissions', 'result')
    op.drop_column('submissions', 'language')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('problems', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('problems', 'memory_limit')
    op.drop_column('problems', 'time_limit')
    op.drop_column('problems', 'output_example')
    op.drop_column('problems', 'input_example')
    op.drop_column('problems', 'output_description')
    op.drop_column('problems', 'input_description')
    op.create_table('boards',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('list_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('write_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('download_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('html_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('use_secret', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('use_dhtml', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('upload_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('boards_pkey'))
    )
    # ### end Alembic commands ###
